<?php

declare(strict_types=1);

namespace Drupal\strata\Estimate;

use JsonSerializable;

/**
 * Whether a projection fits inside what a provider gives away, and how big a site could.
 *
 * The question an operator actually asks first is not what it costs but whether it costs anything,
 * and on R2 the answer is usually no. The free allowance is three separate limits and only one of
 * them binds: storage. Write requests never come close at any interval of five seconds or slower,
 * because the request count depends on the flush interval rather than on the size of the site, and
 * reads are only generated by verification and restore.
 *
 * So the headline is a storage headline, and the capacity figure is found by searching rather than
 * by a formula. Stored bytes are a monotone function of user count with several components that do
 * not scale together - churn scales with active users, the tree scales with subjects, code does not
 * scale at all - so a bisection over the projection is both simpler and more honest than inverting
 * a model that has no inverse.
 *
 * @see Estimator
 * @see PriceTable
 */
final class FreeTierModel implements JsonSerializable
{
	/**
	 * Which limit a projection is closest to using up.
	 */
	public const STORAGE = 'storage';

	/**
	 * The write-request allowance.
	 */
	public const WRITES = 'writes';

	/**
	 * The read-request allowance.
	 */
	public const READS = 'reads';

	/**
	 * Most bisection steps a capacity search takes.
	 *
	 * A bound rather than a tolerance: the search halves an interval, so twenty-four steps resolve a
	 * hundred million users to single figures.
	 */
	public const SEARCH_STEPS = 24;

	/**
	 * Users the capacity search will not look past.
	 */
	public const SEARCH_CEILING = 100_000_000;

	/**
	 * Constructs a verdict.
	 *
	 * @param PriceTable $prices
	 *   The provider being measured against.
	 * @param Projection $projection
	 *   What was projected.
	 */
	public function __construct(
		private readonly PriceTable $prices,
		private readonly Projection $projection,
	) {}

	#region Headroom

	/**
	 * Whether the projection costs nothing.
	 *
	 * @return bool
	 *   TRUE when every axis is inside its allowance.
	 */
	public function fits(): bool
	{
		return $this->prices->hasFreeTier() &&
			$this->projection->totalBytes() <= $this->prices->freeStorageBytes &&
			$this->projection->writesPerMonth <= $this->prices->freeWrites &&
			$this->projection->readsPerMonth <= $this->prices->freeReads;
	}

	/**
	 * What share of one allowance the projection uses.
	 *
	 * @param string $axis
	 *   One of the axis constants.
	 *
	 * @return float
	 *   A fraction, which is above one when the allowance is exceeded and zero when the provider has
	 *   no allowance on that axis.
	 */
	public function usage(string $axis): float
	{
		[$used, $allowance] = match ($axis) {
			self::WRITES => [$this->projection->writesPerMonth, $this->prices->freeWrites],
			self::READS => [$this->projection->readsPerMonth, $this->prices->freeReads],
			default => [$this->projection->totalBytes(), $this->prices->freeStorageBytes],
		};

		return $allowance < 1 ? 0.0 : $used / $allowance;
	}

	/**
	 * How much of one allowance is left.
	 *
	 * @param string $axis
	 *   One of the axis constants.
	 *
	 * @return int
	 *   Bytes or requests, never below zero.
	 */
	public function headroom(string $axis): int
	{
		[$used, $allowance] = match ($axis) {
			self::WRITES => [$this->projection->writesPerMonth, $this->prices->freeWrites],
			self::READS => [$this->projection->readsPerMonth, $this->prices->freeReads],
			default => [$this->projection->totalBytes(), $this->prices->freeStorageBytes],
		};

		return max(0, $allowance - $used);
	}

	/**
	 * Which allowance is closest to being used up.
	 *
	 * @return string
	 *   An axis constant, or an empty string when the provider has no free tier.
	 */
	public function bindingAxis(): string
	{
		if (!$this->prices->hasFreeTier()) {
			return '';
		}

		$axes = [self::STORAGE, self::WRITES, self::READS];
		$binding = self::STORAGE;

		foreach ($axes as $axis) {
			if ($this->usage($axis) > $this->usage($binding)) {
				$binding = $axis;
			}
		}

		return $binding;
	}

	#endregion

	#region Capacity

	/**
	 * The largest user count that still fits in the free tier.
	 *
	 * Everything else about the shape is held still and the user count is varied, because that is the
	 * dial an operator recognises. Nodes and rows are scaled with it in the same proportion the
	 * measurement already has, so a site with ten nodes per user keeps ten nodes per user.
	 *
	 * @param Estimator $estimator
	 *   The estimator to project with.
	 * @param Measurement $shape
	 *   The shape to vary. Its user count is the starting point and is ignored otherwise.
	 * @param PriceTable $prices
	 *   The provider.
	 *
	 * @return int
	 *   Users, or zero when even one user does not fit.
	 */
	public static function capacity(
		Estimator $estimator,
		Measurement $shape,
		PriceTable $prices,
	): int {
		if (!$prices->hasFreeTier()) {
			return 0;
		}

		$nodesPerUser = $shape->users > 0 ? $shape->nodes / $shape->users : 0.0;
		$rowsPerUser = $shape->users > 0 ? $shape->rows / $shape->users : 0.0;

		$at = static function (int $users) use (
			$estimator,
			$shape,
			$prices,
			$nodesPerUser,
			$rowsPerUser,
		): bool {
			$measurement = $shape->with([
				'users' => $users,
				'nodes' => (int) round($users * $nodesPerUser),
				'rows' => (int) round($users * $rowsPerUser),
			]);

			return (new self($prices, $estimator->project($measurement)))->fits();
		};

		if (!$at(1)) {
			return 0;
		}
		if ($at(self::SEARCH_CEILING)) {
			return self::SEARCH_CEILING;
		}

		$low = 1;
		$high = self::SEARCH_CEILING;

		for ($step = 0; $step < self::SEARCH_STEPS && $high - $low > 1; $step++) {
			$middle = intdiv($low + $high, 2);

			if ($at($middle)) {
				$low = $middle;

				continue;
			}

			$high = $middle;
		}

		return $low;
	}

	#endregion

	/**
	 * One line describing the verdict.
	 *
	 * @return string
	 *   The summary.
	 */
	public function summary(): string
	{
		if (!$this->prices->hasFreeTier()) {
			return sprintf('%s has no free allowance', $this->prices->label);
		}

		return sprintf(
			'%s on %s: %.0f%% of the storage allowance, %.0f%% of the write allowance, %s binding',
			$this->fits() ? 'free' : 'over the allowance',
			$this->prices->label,
			$this->usage(self::STORAGE) * 100,
			$this->usage(self::WRITES) * 100,
			$this->bindingAxis(),
		);
	}

	/**
	 * {@inheritdoc}
	 *
	 * @return array<string, mixed>
	 *   The verdict as data.
	 */
	public function jsonSerialize(): array
	{
		return [
			'provider' => $this->prices->id,
			'fits' => $this->fits(),
			'binding_axis' => $this->bindingAxis(),
			'usage' => [
				self::STORAGE => $this->usage(self::STORAGE),
				self::WRITES => $this->usage(self::WRITES),
				self::READS => $this->usage(self::READS),
			],
			'headroom' => [
				self::STORAGE => $this->headroom(self::STORAGE),
				self::WRITES => $this->headroom(self::WRITES),
				self::READS => $this->headroom(self::READS),
			],
		];
	}
}
